package coder;


/**
* coder/CoderPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from coder.idl
* 17 марта 2022 г. 0:10:41 MSK
*/

public abstract class CoderPOA extends org.omg.PortableServer.Servant
 implements coder.CoderOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_code", new java.lang.Integer (0));
    _methods.put ("_set_code", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // coder/Coder/_get_code
       {
         String $result = null;
         $result = this.code ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // coder/Coder/_set_code
       {
         String newCode = in.read_string ();
         this.code (newCode);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:coder/Coder:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Coder _this() 
  {
    return CoderHelper.narrow(
    super._this_object());
  }

  public Coder _this(org.omg.CORBA.ORB orb) 
  {
    return CoderHelper.narrow(
    super._this_object(orb));
  }


} // class CoderPOA
