package coder;

/**
* coder/CoderHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from coder.idl
* 17 марта 2022 г. 0:10:41 MSK
*/

public final class CoderHolder implements org.omg.CORBA.portable.Streamable
{
  public coder.Coder value = null;

  public CoderHolder ()
  {
  }

  public CoderHolder (coder.Coder initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = coder.CoderHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    coder.CoderHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return coder.CoderHelper.type ();
  }

}
