package coder;


/**
* coder/Coder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from coder.idl
* 17 марта 2022 г. 0:10:41 MSK
*/

public interface Coder extends CoderOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Coder
