package coder;


/**
* coder/CoderOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from coder.idl
* 17 марта 2022 г. 0:10:41 MSK
*/

public interface CoderOperations 
{
  String code ();
  void code (String newCode);
} // interface CoderOperations
