package coder;


/**
* coder/DecoderOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from decoder.idl
* 17 марта 2022 г. 0:10:49 MSK
*/

public interface DecoderOperations 
{
  String decode ();
  void decode (String newDecode);
} // interface DecoderOperations
