package coder;

/**
* coder/DecoderHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from decoder.idl
* 17 марта 2022 г. 0:10:49 MSK
*/

public final class DecoderHolder implements org.omg.CORBA.portable.Streamable
{
  public coder.Decoder value = null;

  public DecoderHolder ()
  {
  }

  public DecoderHolder (coder.Decoder initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = coder.DecoderHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    coder.DecoderHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return coder.DecoderHelper.type ();
  }

}
