package coder;


/**
* coder/Decoder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from decoder.idl
* 17 марта 2022 г. 0:10:49 MSK
*/

public interface Decoder extends DecoderOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Decoder
