package coder;


/**
* coder/DecoderHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from decoder.idl
* 17 марта 2022 г. 0:10:49 MSK
*/

abstract public class DecoderHelper
{
  private static String  _id = "IDL:coder/Decoder:1.0";

  public static void insert (org.omg.CORBA.Any a, coder.Decoder that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static coder.Decoder extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (coder.DecoderHelper.id (), "Decoder");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static coder.Decoder read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DecoderStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, coder.Decoder value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static coder.Decoder narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof coder.Decoder)
      return (coder.Decoder)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      coder._DecoderStub stub = new coder._DecoderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static coder.Decoder unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof coder.Decoder)
      return (coder.Decoder)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      coder._DecoderStub stub = new coder._DecoderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
